--- #YAML:1.0
name:               Mojolicious-Plugin-ContentManagement
version:            0.013
abstract:           Content management for Mojolicious
author:
    - Mirko Westermeier <mail@memowe.de>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::SQLite:     1.29
    DBI:             1.61
    Mojolicious:     1.3
    Text::Markdown:  1.000031
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
