--- #YAML:1.0
name:               Mojolicious-Plugin-ContentManagement
version:            0.01
abstract:           Content management for Mojolicious
author:
    - Mirko Westermeier <mail@memowe.de>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBI:                  1.6
    Mojolicious:          0.9999
    Test::More:           0
    Test::WWW::Mechanize::Mojo:  0.0.4
    Text::Markdown:       1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
